"""Added ip and geo fields

Revision ID: 001c84acb3a4
Revises: f9d49b3c61cb
Create Date: 2025-07-11 17:09:45.026750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001c84acb3a4'
down_revision: Union[str, Sequence[str], None] = 'f9d49b3c61cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('ip_address', sa.String(length=15), nullable=True))
    op.add_column('complaints', sa.Column('geo_country', sa.String(length=50), nullable=True))
    op.add_column('complaints', sa.Column('geo_city', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'geo_city')
    op.drop_column('complaints', 'geo_country')
    op.drop_column('complaints', 'ip_address')
    # ### end Alembic commands ###
